# Generated by Django 2.2.4 on 2019-08-07 12:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Brand', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Category', models.CharField(max_length=255)),
                ('Slug_Category', models.SlugField()),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name_Product', models.CharField(max_length=255)),
                ('Slug', models.SlugField()),
                ('Price_Import', models.IntegerField()),
                ('Price_Old', models.IntegerField()),
                ('Price_New', models.IntegerField()),
                ('Wage', models.IntegerField()),
                ('Quality', models.IntegerField()),
                ('Decription', models.TextField()),
                ('Date_Create', models.DateTimeField(auto_now_add=True)),
                ('Date_Update', models.DateTimeField(auto_now=True)),
                ('Active', models.BooleanField(default=True)),
                ('Brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand')),
            ],
        ),
        migrations.AddField(
            model_name='brand',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category'),
        ),
    ]
