# Generated by Django 2.2.4 on 2019-08-07 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='Name_Category',
            field=models.CharField(max_length=255, verbose_name='Tên loại'),
        ),
    ]
