# Generated by Django 2.2.4 on 2019-08-07 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_auto_20190807_1937'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brand',
            name='Category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Loại'),
        ),
        migrations.AlterField(
            model_name='brand',
            name='Name_Brand',
            field=models.CharField(max_length=255, verbose_name='Tên Thương Hiệu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Name_Category',
            field=models.CharField(max_length=255, verbose_name='Tên Loại'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Slug_Category',
            field=models.SlugField(verbose_name='Từ Khóa Loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='Kích Hoạt'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Brand',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Brand', verbose_name='Thương Hiệu'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Date_Update',
            field=models.DateTimeField(auto_now=True, verbose_name='Ngày Sửa'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Decription',
            field=models.TextField(verbose_name='Mô Tả'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Name_Product',
            field=models.CharField(max_length=255, verbose_name='Tên Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Import',
            field=models.IntegerField(verbose_name='Giá Nhập Hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_New',
            field=models.IntegerField(verbose_name='Giá Bán Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Old',
            field=models.IntegerField(verbose_name='Giá Bán Cũ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quality',
            field=models.IntegerField(verbose_name='Số Lượng Còn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(verbose_name='Từ Khóa Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wage',
            field=models.IntegerField(verbose_name='Tiền Công'),
        ),
    ]
