# Generated by Django 2.2.4 on 2019-08-07 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20190807_1941'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name_plural': 'Thương Hiệu'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name_plural': 'Loại Sản Phẩm'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Sản Phẩm'},
        ),
    ]
