# Generated by Django 2.2.4 on 2019-08-10 01:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20190807_1948'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='Slug_Brand',
            field=models.SlugField(blank=True, unique=True, verbose_name='Từ khóa thương hiệu'),
        ),
        migrations.AlterField(
            model_name='category',
            name='Slug_Category',
            field=models.SlugField(blank=True, unique=True, verbose_name='Từ Khóa Loại'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Slug',
            field=models.SlugField(blank=True, unique=True, verbose_name='Từ Khóa Sản Phẩm'),
        ),
    ]
