# Generated by Django 2.2.4 on 2019-08-11 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0007_auto_20190811_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_Import',
            field=models.CharField(max_length=3, verbose_name='Giá Nhập Hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_New',
            field=models.CharField(max_length=3, verbose_name='Giá Bán Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Old',
            field=models.CharField(max_length=3, verbose_name='Giá Bán Cũ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quality',
            field=models.CharField(max_length=3, verbose_name='Số Lượng Còn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wage',
            field=models.CharField(max_length=3, verbose_name='Tiền Công'),
        ),
    ]
