# Generated by Django 2.2.4 on 2019-08-11 04:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0009_auto_20190811_1053'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_Import',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá Nhập Hàng'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_New',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá Bán Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Old',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá Bán Cũ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Quality',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Số Lượng Còn'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wage',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tiền Công'),
        ),
    ]
