# Generated by Django 2.2.4 on 2019-08-11 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0010_auto_20190811_1106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='Category',
        ),
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brand', verbose_name='Thương Hiệu'),
            preserve_default=False,
        ),
    ]
