# Generated by Django 2.2.4 on 2019-08-11 04:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_remove_category_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='brand',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='product.Brand', verbose_name='Thương Hiệu'),
        ),
    ]
