# Generated by Django 2.2.4 on 2019-08-11 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0016_remove_category_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='Category',
            field=models.ForeignKey(default=True, on_delete=django.db.models.deletion.CASCADE, to='product.Category', verbose_name='Loại Sản Phẩm'),
            preserve_default=False,
        ),
    ]
