# Generated by Django 2.2.4 on 2019-08-11 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Active',
            field=models.BooleanField(default=True, verbose_name='Kích Hoạt'),
        ),
    ]
