# Generated by Django 2.2.4 on 2019-08-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0021_auto_20190811_1914'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Quality',
            field=models.IntegerField(blank=True, null=True, verbose_name='Số Lượng Còn'),
        ),
    ]
