# Generated by Django 2.2.4 on 2019-08-16 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190811_1915'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_Import',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Nhập Hàng'),
        ),
    ]
