# Generated by Django 2.2.4 on 2019-08-16 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_auto_20190816_1130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='Price_New',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Bán Mới'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Price_Old',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá Bán Cũ'),
        ),
        migrations.AlterField(
            model_name='product',
            name='Wage',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Tiền Công'),
        ),
    ]
