# Generated by Django 2.2.4 on 2019-08-16 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0025_auto_20190816_1131'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='Price',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá'),
        ),
    ]
