# Generated by Django 2.2.4 on 2019-08-11 11:39

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0019_auto_20190811_1819'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date_Create', models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo')),
                ('Total_Money', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Tổng Tiền')),
                ('Sale', models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)], verbose_name='Giảm Giá')),
                ('Active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Hóa Đơn',
            },
        ),
        migrations.CreateModel(
            name='Bill_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.IntegerField(default=1, verbose_name='Số Lượng')),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Service')),
            ],
            options={
                'verbose_name_plural': 'Hóa Đơn Dịch Vụ',
            },
        ),
        migrations.CreateModel(
            name='Bill_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.IntegerField(default=1, verbose_name='Số Lượng')),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Sản Phẩm')),
            ],
            options={
                'verbose_name_plural': 'Hóa Đơn Sản Phầm',
            },
        ),
    ]
