# Generated by Django 2.2.4 on 2019-08-11 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_auto_20190811_1819'),
        ('bill', '0002_bill_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill_product',
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='bill_product',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='bill_service',
            name='Bill',
        ),
        migrations.RemoveField(
            model_name='bill_service',
            name='Service',
        ),
        migrations.AddField(
            model_name='bill',
            name='Product',
            field=models.ManyToManyField(to='product.Product', verbose_name='Sản Phẩm'),
        ),
        migrations.AddField(
            model_name='bill',
            name='Service',
            field=models.ManyToManyField(to='product.Service', verbose_name='Dịch Vụ'),
        ),
        migrations.DeleteModel(
            name='Bill_Product',
        ),
        migrations.DeleteModel(
            name='Bill_Service',
        ),
    ]
