# Generated by Django 2.2.4 on 2019-08-11 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0004_auto_20190811_1905'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Product',
            field=models.ManyToManyField(blank=True, to='product.Product', verbose_name='Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Service',
            field=models.ManyToManyField(blank=True, to='product.Service', verbose_name='Dịch Vụ'),
        ),
    ]
