# Generated by Django 2.2.4 on 2019-08-11 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0005_auto_20190811_1911'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Product',
            field=models.ManyToManyField(to='product.Product', verbose_name='Sản Phẩm'),
        ),
        migrations.AlterField(
            model_name='bill',
            name='Service',
            field=models.ManyToManyField(to='product.Service', verbose_name='Dịch Vụ'),
        ),
    ]
