# Generated by Django 2.2.4 on 2019-08-11 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_auto_20190811_1915'),
        ('bill', '0008_auto_20190811_1916'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bill',
            name='Product',
        ),
        migrations.RemoveField(
            model_name='bill',
            name='Service',
        ),
        migrations.CreateModel(
            name='Bill_Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.IntegerField(default=1, verbose_name='Số Lượng')),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('Service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Service')),
            ],
            options={
                'verbose_name_plural': 'Hóa Đơn Dịch Vụ',
            },
        ),
        migrations.CreateModel(
            name='Bill_Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quality', models.IntegerField(default=1, verbose_name='Số Lượng')),
                ('Bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='bill.Bill')),
                ('Product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.Product', verbose_name='Sản Phẩm')),
            ],
            options={
                'verbose_name_plural': 'Hóa Đơn Sản Phầm',
            },
        ),
    ]
