# Generated by Django 2.2.4 on 2019-08-11 12:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0009_auto_20190811_1918'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Date_Create',
            field=models.DateTimeField(default=datetime.datetime(2019, 8, 11, 12, 25, 43, 141550, tzinfo=utc), verbose_name='Ngày Tạo'),
        ),
    ]
