# Generated by Django 2.2.4 on 2019-08-11 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0010_auto_20190811_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Date_Create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo'),
        ),
    ]
