# Generated by Django 2.2.4 on 2019-08-23 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bill', '0013_auto_20190823_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='Date_Create',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Ngày Tạo'),
        ),
    ]
